version: "3"
services:
  balancer:
    image: nginx:latest
    volumes:
      - "./:/var/www/src"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - php
    ports:
      - "8080:80"
    restart: always

  php:
    image: php:7.4-fpm
    ports:
      - "3000:3000"
    volumes:
      - ".:/var/www/filterflix"
    restart: always

  composer:
    restart: always
    image: composer
    command: install
    depends_on:
      - php
    volumes:
       - ".:/app"
