name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: php bin/phpunit

    - name: Codecov generate
      run: bash <(curl -s https://codecov.io/bash)
    
    - name: Coverage      
      with:
          token: ${{ secrets.CODECOV }}
